# Generated by Django 5.0 on 2023-12-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_categoriavideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='infovideos',
            name='categoiaId',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
