# Generated by Django 5.0 on 2023-12-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_categoiaid_infovideos_categoriaid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaVideos',
            new_name='CategoriaVideo',
        ),
        migrations.RenameModel(
            old_name='InfoVideos',
            new_name='Video',
        ),
    ]
